name: Windows Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    name: Build Windows App

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # uprav podle potřeby

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish self-contained app
        run: dotnet publish TestySZP/TestySZP.csproj --configuration Release --runtime win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true -o publish

      - name: Set ZIP filename
        id: zipname
        run: echo "ZIP_NAME=TestySZP-${{ github.event.release.tag_name }}-win-x64.zip" >> $env:GITHUB_ENV

      - name: Create ZIP archive
        run: Compress-Archive -Path publish\* -DestinationPath ${{ env.ZIP_NAME }}

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
