name: Windows Release (.NET framework-dependent)

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    name: Build Windows App (non-self-contained)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # uprav podle své verze

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish framework-dependent build
        run: dotnet publish TestySZP/TestySZP.csproj --configuration Release --output publish

      - name: Set ZIP filename
        id: zipname
        run: echo "ZIP_NAME=TestySZP-${{ github.event.release.tag_name }}-win-x64.zip" >> $env:GITHUB_ENV

      - name: Create ZIP archive
        run: Compress-Archive -Path publish\* -DestinationPath $env:ZIP_NAME

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
